import 'package:flutter/material.dart';


// Documentation: 
/*
Colors from https://material.io/design/color/the-color-system.html#tools-for-picking-colors
based on payoprint's Colors Guidance https://www.figma.com/file/ZWr3LxiaIimf3WJz1VVF9M/UXUI-PP?type=design&node-id=339-452&mode=design&t=drp26P89QKQw18y3-0
Generated by http://mcg.mbitson.com/
*/



// Primary color
const MaterialColor primary = MaterialColor(_primaryPrimaryValue, <int, Color>{
  50: Color(0xFFCCEEF7),
  100: Color(0xFF8AD8ED),
  200: Color(0xFF59C8E5),
  300: Color(0xFF21B1D6),
  400: Color(0xFF1D9BBB),
  500: Color(_primaryPrimaryValue),
  600: Color(0xFF156F87),
  700: Color(0xFF11596C),
  800: Color(0xFF0D4352),
  900: Color(0xFF092D37),
});
const int _primaryPrimaryValue = 0xFF1985A1;

const MaterialColor primaryAccent = MaterialColor(_primaryAccentValue, <int, Color>{
  100: Color(0xFFBAF1FF),
  200: Color(_primaryAccentValue),
  400: Color(0xFF0EB4DF),
  700: Color(0xFF179ABC),
});
const int _primaryAccentValue = 0xFF54DCFF;


// secondary color
const MaterialColor secondary = MaterialColor(_secondaryPrimaryValue, <int, Color>{
  50: Color(0xFFFFFFFF),
  100: Color(0xFFFFFFFF),
  200: Color(0xFFFFFFFF),
  300: Color(0xFFE3E2E4),
  400: Color(0xFFD4D3D5),
  500: Color(_secondaryPrimaryValue),
  600: Color(0xFFB6B3B7),
  700: Color(0xFFA7A4A8),
  800: Color(0xFF979499),
  900: Color(0xFF88848A),
});
const int _secondaryPrimaryValue = 0xFFC5C3C6;

const MaterialColor secondaryAccent = MaterialColor(_secondaryAccentValue, <int, Color>{
  100: Color(0xFFFFFFFF),
  200: Color(_secondaryAccentValue),
  400: Color(0xFFE0D8E4),
  700: Color(0xFFD2CED5),
});
const int _secondaryAccentValue = 0xFFFFFFFF;


// Neutral color
const MaterialColor neutral = MaterialColor(_neutralPrimaryValue, <int, Color>{
  50: Color(0xFFA7AFB5),
  100: Color(0xFF7E8992),
  200: Color(0xFF636D75),
  300: Color(0xFF42494E),
  400: Color(0xFF34393E),
  500: Color(_neutralPrimaryValue),
  600: Color(0xFF181B1C),
  700: Color(0xFF0A0B0C),
  800: Color(0xFF000000),
  900: Color(0xFF000000),
});
const int _neutralPrimaryValue = 0xFF262A2D;

const MaterialColor neutralAccent = MaterialColor(_neutralAccentValue, <int, Color>{
  100: Color(0xFF88AECA),
  200: Color(_neutralAccentValue),
  400: Color(0xFF334553),
  700: Color(0xFF2F373E),
});
const int _neutralAccentValue = 0xFF497CA3;


// Error color
const MaterialColor error = MaterialColor(_errorPrimaryValue, <int, Color>{
  50: Color(0xFFFFFFFF),
  100: Color(0xFFF8D9D7),
  200: Color(0xFFEFADA7),
  300: Color(0xFFE4746B),
  400: Color(0xFFE05C51),
  500: Color(_errorPrimaryValue),
  600: Color(0xFFCE3325),
  700: Color(0xFFB42C20),
  800: Color(0xFF9A261C),
  900: Color(0xFF801F17),
});
const int _errorPrimaryValue = 0xFFDB4437;

const MaterialColor errorAccent = MaterialColor(_errorAccentValue, <int, Color>{
  100: Color(0xFFFFFFFF),
  200: Color(_errorAccentValue),
  400: Color(0xFFF16154),
  700: Color(0xFFE45447),
});
const int _errorAccentValue = 0xFFFFB3AC;


// Warning color
const MaterialColor warning = MaterialColor(_warningPrimaryValue, <int, Color>{
  50: Color(0xFFFFFFFE),
  100: Color(0xFFFFEBB2),
  200: Color(0xFFFFDC7A),
  300: Color(0xFFFFC932),
  400: Color(0xFFFFC114),
  500: Color(_warningPrimaryValue),
  600: Color(0xFFD59D00),
  700: Color(0xFFB78700),
  800: Color(0xFF987000),
  900: Color(0xFF7A5A00),
});
const int _warningPrimaryValue = 0xFFF4B400;

const MaterialColor warningAccent = MaterialColor(_warningAccentValue, <int, Color>{
  100: Color(0xFFFFFCF4),
  200: Color(_warningAccentValue),
  400: Color(0xFFFFC728),
  700: Color(0xFFFFC00E),
});
const int _warningAccentValue = 0xFFFFE18E;